CREATE DATABASE IF NOT EXISTS oficina;
USE oficina;


CREATE TABLE CLIENTE(
    idCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45),
    CPF_CNPJ VARCHAR(45),
    ENDERECO VARCHAR(200)
);


CREATE TABLE VEICULO(
    idVEICULO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    MARCA VARCHAR(45),
    MODELO VARCHAR(45),
    PLACA VARCHAR(45),
    ANO INT,
    CONSTRAINT fk_veiculo_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(idCLIENTE)
);


CREATE TABLE EQUIPE(
    idEQUIPE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45)
);


CREATE TABLE MECANICO(
    idMECANICO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45),
    ESPECIALIDADE VARCHAR(45),
    ENDERECO VARCHAR(45),
    ID_EQUIPE INT,
    CONSTRAINT fk_mecanico_equipe FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(idEQUIPE)
);


CREATE TABLE OS(
    idOS INT AUTO_INCREMENT PRIMARY KEY,
    ID_VEICULO INT,
    ID_EQUIPE INT,
    DATA_EMISSAO DATE,
    DATA_CONCLUSAO DATE,
    STATUS VARCHAR(45),
    VALOR_TOTAL DECIMAL(10,2),
    CONSTRAINT fk_os_veiculo FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(idVEICULO),
    CONSTRAINT fk_os_equipe FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(idEQUIPE)
);


CREATE TABLE SERVICO(
    idSERVICO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(45),
    VALOR_MAO_DE_OBRA DECIMAL(10,2)
);


CREATE TABLE TIPO_DE_SERVICO(
    OS_idOS INT,
    SERVICO_idSERVICO INT,
    PRIMARY KEY (OS_idOS, SERVICO_idSERVICO),
    CONSTRAINT fk_tipo_os FOREIGN KEY (OS_idOS) REFERENCES OS(idOS),
    CONSTRAINT fk_tipo_servico FOREIGN KEY (SERVICO_idSERVICO) REFERENCES SERVICO(idSERVICO)
);


CREATE TABLE OS_SERVICO(
    IDOS INT,
    IDSERVICO INT,
    QUANTIDADE INT,
    PRIMARY KEY (IDOS, IDSERVICO),
    CONSTRAINT fk_osservico_os FOREIGN KEY (IDOS) REFERENCES OS(idOS),
    CONSTRAINT fk_osservico_servico FOREIGN KEY (IDSERVICO) REFERENCES SERVICO(idSERVICO)
);


CREATE TABLE PECA(
    idPECA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PECA VARCHAR(45),
    VALOR DECIMAL(10,2)
);


CREATE TABLE OS_PECA(
    idOS_PECA INT AUTO_INCREMENT PRIMARY KEY,
    OS_idOS INT,
    PECA_idPECA INT,
    QUANTIDADE INT,
    CONSTRAINT fk_ospeca_os FOREIGN KEY (OS_idOS) REFERENCES OS(idOS),
    CONSTRAINT fk_ospeca_peca FOREIGN KEY (PECA_idPECA) REFERENCES PECA(idPECA)
);


CREATE TABLE PEDIDOS_DE_PECAS(
    OS_idOS INT,
    OS_PECA_idOS_PECA INT,
    PRIMARY KEY (OS_idOS, OS_PECA_idOS_PECA),
    CONSTRAINT fk_pedidos_os FOREIGN KEY (OS_idOS) REFERENCES OS(idOS),
    CONSTRAINT fk_pedidos_ospeca FOREIGN KEY (OS_PECA_idOS_PECA) REFERENCES OS_PECA(idOS_PECA)
);


CREATE TABLE DISPONIBILIDADE_DE_PEÇAS(
    OS_PECA_idOS_PECA INT,
    PECA_idPECA INT,
    PRIMARY KEY (OS_PECA_idOS_PECA, PECA_idPECA),
    CONSTRAINT fk_disp_ospeca FOREIGN KEY (OS_PECA_idOS_PECA) REFERENCES OS_PECA(idOS_PECA),
    CONSTRAINT fk_disp_peca FOREIGN KEY (PECA_idPECA) REFERENCES PECA(idPECA)
);
